{
    "name": "Korventis Partner DGII",
    "summary": "Padrón local DGII y registro asistido de clientes dominicanos",
    "version": "18.0.1.1.0",
    "category": "Sales/CRM",
    "author": "Korventis",
    "website": "https://github.com/yoryijose90r/odoo-korventis-fiscal-rd",
    "license": "Other proprietary",
    "depends": [
        "contacts",
        "partner_autocomplete",
        "korventis_l10n_do_fiscal",
    ],
    "data": [
        "security/dgii_security.xml",
        "security/ir.model.access.csv",
        "data/dgii_config.xml",
        "data/dgii_cron.xml",
        "views/dgii_status_views.xml",
        "views/dgii_rnc_views.xml",
        "views/dgii_version_views.xml",
        "views/dgii_import_run_views.xml",
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "wizard/partner_lookup_views.xml",
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
}
